name: Nonscheduled build (Windows / MSYS2)

on:
  push:
    branches: [reg-ci]

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: mingw-w64-x86_64-cmake mingw-w64-x86_64-meson mingw-w64-x86_64-gcc mingw-w64-x86_64-vapoursynth mingw-w64-x86_64-gsl

    - name: Configure and build
      run: |
        meson setup builddir --buildtype release
        meson compile -C builddir

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: bore-win64
        path: builddir/libbore.dll
